// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/follower.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FollowerId       string                 `protobuf:"bytes,1,opt,name=followerId,proto3" json:"followerId,omitempty"`
	FollowedId       string                 `protobuf:"bytes,2,opt,name=followedId,proto3" json:"followedId,omitempty"`
	FollowerUsername string                 `protobuf:"bytes,3,opt,name=followerUsername,proto3" json:"followerUsername,omitempty"`
	FollowedUsername string                 `protobuf:"bytes,4,opt,name=followedUsername,proto3" json:"followedUsername,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_proto_follower_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_follower_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowRequest) GetFollowedId() string {
	if x != nil {
		return x.FollowedId
	}
	return ""
}

func (x *FollowRequest) GetFollowerUsername() string {
	if x != nil {
		return x.FollowerUsername
	}
	return ""
}

func (x *FollowRequest) GetFollowedUsername() string {
	if x != nil {
		return x.FollowedUsername
	}
	return ""
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_proto_follower_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_follower_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FollowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=followerId,proto3" json:"followerId,omitempty"`
	FollowedId    string                 `protobuf:"bytes,2,opt,name=followedId,proto3" json:"followedId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_proto_follower_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_follower_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *UnfollowRequest) GetFollowedId() string {
	if x != nil {
		return x.FollowedId
	}
	return ""
}

type UnfollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_proto_follower_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_follower_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnfollowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_proto_follower_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_proto_follower_proto_rawDescGZIP(), []int{4}
}

func (x *GetFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProto) Reset() {
	*x = UserProto{}
	mi := &file_proto_follower_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProto) ProtoMessage() {}

func (x *UserProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProto.ProtoReflect.Descriptor instead.
func (*UserProto) Descriptor() ([]byte, []int) {
	return file_proto_follower_proto_rawDescGZIP(), []int{5}
}

func (x *UserProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserProto           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_proto_follower_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_proto_follower_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowingResponse) GetUsers() []*UserProto {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proto_follower_proto protoreflect.FileDescriptor

const file_proto_follower_proto_rawDesc = "" +
	"\n" +
	"\x14proto/follower.proto\"\xa7\x01\n" +
	"\rFollowRequest\x12\x1e\n" +
	"\n" +
	"followerId\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1e\n" +
	"\n" +
	"followedId\x18\x02 \x01(\tR\n" +
	"followedId\x12*\n" +
	"\x10followerUsername\x18\x03 \x01(\tR\x10followerUsername\x12*\n" +
	"\x10followedUsername\x18\x04 \x01(\tR\x10followedUsername\"@\n" +
	"\x0eFollowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Q\n" +
	"\x0fUnfollowRequest\x12\x1e\n" +
	"\n" +
	"followerId\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1e\n" +
	"\n" +
	"followedId\x18\x02 \x01(\tR\n" +
	"followedId\"B\n" +
	"\x10UnfollowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x13GetFollowingRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\tUserProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"8\n" +
	"\x14GetFollowingResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".UserProtoR\x05users2\xb0\x01\n" +
	"\x0fFollowerService\x12+\n" +
	"\x06Follow\x12\x0e.FollowRequest\x1a\x0f.FollowResponse\"\x00\x121\n" +
	"\bUnfollow\x12\x10.UnfollowRequest\x1a\x11.UnfollowResponse\"\x00\x12=\n" +
	"\fGetFollowing\x12\x14.GetFollowingRequest\x1a\x15.GetFollowingResponse\"\x00B\x18Z\x16follower-service/protob\x06proto3"

var (
	file_proto_follower_proto_rawDescOnce sync.Once
	file_proto_follower_proto_rawDescData []byte
)

func file_proto_follower_proto_rawDescGZIP() []byte {
	file_proto_follower_proto_rawDescOnce.Do(func() {
		file_proto_follower_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_follower_proto_rawDesc), len(file_proto_follower_proto_rawDesc)))
	})
	return file_proto_follower_proto_rawDescData
}

var file_proto_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_follower_proto_goTypes = []any{
	(*FollowRequest)(nil),        // 0: FollowRequest
	(*FollowResponse)(nil),       // 1: FollowResponse
	(*UnfollowRequest)(nil),      // 2: UnfollowRequest
	(*UnfollowResponse)(nil),     // 3: UnfollowResponse
	(*GetFollowingRequest)(nil),  // 4: GetFollowingRequest
	(*UserProto)(nil),            // 5: UserProto
	(*GetFollowingResponse)(nil), // 6: GetFollowingResponse
}
var file_proto_follower_proto_depIdxs = []int32{
	5, // 0: GetFollowingResponse.users:type_name -> UserProto
	0, // 1: FollowerService.Follow:input_type -> FollowRequest
	2, // 2: FollowerService.Unfollow:input_type -> UnfollowRequest
	4, // 3: FollowerService.GetFollowing:input_type -> GetFollowingRequest
	1, // 4: FollowerService.Follow:output_type -> FollowResponse
	3, // 5: FollowerService.Unfollow:output_type -> UnfollowResponse
	6, // 6: FollowerService.GetFollowing:output_type -> GetFollowingResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_follower_proto_init() }
func file_proto_follower_proto_init() {
	if File_proto_follower_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_follower_proto_rawDesc), len(file_proto_follower_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_follower_proto_goTypes,
		DependencyIndexes: file_proto_follower_proto_depIdxs,
		MessageInfos:      file_proto_follower_proto_msgTypes,
	}.Build()
	File_proto_follower_proto = out.File
	file_proto_follower_proto_goTypes = nil
	file_proto_follower_proto_depIdxs = nil
}
