spring.application.name=blog
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/blog_db}
server.port=${SERVER_PORT:8082}

spring.web.resources.static-locations=classpath:/static/,file:./uploads/
spring.servlet.multipart.max-file-size=10MB

follower-service.url=${FOLLOWER_SERVICE_URL:http://localhost:8084}