syntax = "proto3";

option go_package = "payment-service/proto";

service PaymentService {
  rpc GetPurchases (GetPurchasesRequest) returns (GetPurchasesResponse) {}
  rpc Checkout     (CheckoutRequest)     returns (CheckoutResponse)     {}
}

message TourPurchaseToken {
  string id          = 1;
  int64  touristId   = 2;
  string tourId      = 3;
  string tourName    = 4;
  double price       = 5;
  string purchasedAt = 6;
}

message GetPurchasesRequest {
  int64 touristId = 1;
}

message GetPurchasesResponse {
  repeated TourPurchaseToken tokens = 1;
}

message CheckoutRequest {
  int64 touristId = 1;
}

message CheckoutResponse {
  repeated TourPurchaseToken tokens = 1;
  string error                      = 2;
}
