// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: tour-service.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportType string                 `protobuf:"bytes,1,opt,name=transportType,proto3" json:"transportType,omitempty"`
	Minutes       int32                  `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportTime) Reset() {
	*x = TransportTime{}
	mi := &file_tour_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportTime) ProtoMessage() {}

func (x *TransportTime) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportTime.ProtoReflect.Descriptor instead.
func (*TransportTime) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{0}
}

func (x *TransportTime) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *TransportTime) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type Tour struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId       int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	AuthorUsername string                 `protobuf:"bytes,3,opt,name=authorUsername,proto3" json:"authorUsername,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty     string                 `protobuf:"bytes,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags           []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Price          float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	LengthKm       float64                `protobuf:"fixed64,10,opt,name=lengthKm,proto3" json:"lengthKm,omitempty"`
	TransportTimes []*TransportTime       `protobuf:"bytes,11,rep,name=transportTimes,proto3" json:"transportTimes,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	PublishedAt    string                 `protobuf:"bytes,13,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	ArchivedAt     string                 `protobuf:"bytes,14,opt,name=archivedAt,proto3" json:"archivedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tour_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{1}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Tour) GetAuthorUsername() string {
	if x != nil {
		return x.AuthorUsername
	}
	return ""
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetLengthKm() float64 {
	if x != nil {
		return x.LengthKm
	}
	return 0
}

func (x *Tour) GetTransportTimes() []*TransportTime {
	if x != nil {
		return x.TransportTimes
	}
	return nil
}

func (x *Tour) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Tour) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Tour) GetArchivedAt() string {
	if x != nil {
		return x.ArchivedAt
	}
	return ""
}

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_tour_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTourByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTourByIdRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetTourByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTourByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdResponse) Reset() {
	*x = GetTourByIdResponse{}
	mi := &file_tour_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdResponse) ProtoMessage() {}

func (x *GetTourByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTourByIdResponse) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTourByIdResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type PublishTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTourRequest) Reset() {
	*x = PublishTourRequest{}
	mi := &file_tour_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourRequest) ProtoMessage() {}

func (x *PublishTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourRequest.ProtoReflect.Descriptor instead.
func (*PublishTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{4}
}

func (x *PublishTourRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishTourRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type PublishTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTourResponse) Reset() {
	*x = PublishTourResponse{}
	mi := &file_tour_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourResponse) ProtoMessage() {}

func (x *PublishTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourResponse.ProtoReflect.Descriptor instead.
func (*PublishTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_service_proto_rawDescGZIP(), []int{5}
}

func (x *PublishTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

func (x *PublishTourResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tour_service_proto protoreflect.FileDescriptor

const file_tour_service_proto_rawDesc = "" +
	"\n" +
	"\x12tour-service.proto\x1a\x1cgoogle/api/annotations.proto\"O\n" +
	"\rTransportTime\x12$\n" +
	"\rtransportType\x18\x01 \x01(\tR\rtransportType\x12\x18\n" +
	"\aminutes\x18\x02 \x01(\x05R\aminutes\"\xa6\x03\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\x12&\n" +
	"\x0eauthorUsername\x18\x03 \x01(\tR\x0eauthorUsername\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12\x1a\n" +
	"\blengthKm\x18\n" +
	" \x01(\x01R\blengthKm\x126\n" +
	"\x0etransportTimes\x18\v \x03(\v2\x0e.TransportTimeR\x0etransportTimes\x12\x1c\n" +
	"\tcreatedAt\x18\f \x01(\tR\tcreatedAt\x12 \n" +
	"\vpublishedAt\x18\r \x01(\tR\vpublishedAt\x12\x1e\n" +
	"\n" +
	"archivedAt\x18\x0e \x01(\tR\n" +
	"archivedAt\"P\n" +
	"\x12GetTourByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\"0\n" +
	"\x13GetTourByIdResponse\x12\x19\n" +
	"\x04tour\x18\x01 \x01(\v2\x05.TourR\x04tour\"@\n" +
	"\x12PublishTourRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\"F\n" +
	"\x13PublishTourResponse\x12\x19\n" +
	"\x04tour\x18\x01 \x01(\v2\x05.TourR\x04tour\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xbe\x01\n" +
	"\vTourService\x12Q\n" +
	"\vGetTourById\x12\x13.GetTourByIdRequest\x1a\x14.GetTourByIdResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/tours/{id}\x12\\\n" +
	"\vPublishTour\x12\x13.PublishTourRequest\x1a\x14.PublishTourResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/tours/{id}/publishB\x14Z\x12tour-service/protob\x06proto3"

var (
	file_tour_service_proto_rawDescOnce sync.Once
	file_tour_service_proto_rawDescData []byte
)

func file_tour_service_proto_rawDescGZIP() []byte {
	file_tour_service_proto_rawDescOnce.Do(func() {
		file_tour_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tour_service_proto_rawDesc), len(file_tour_service_proto_rawDesc)))
	})
	return file_tour_service_proto_rawDescData
}

var file_tour_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tour_service_proto_goTypes = []any{
	(*TransportTime)(nil),       // 0: TransportTime
	(*Tour)(nil),                // 1: Tour
	(*GetTourByIdRequest)(nil),  // 2: GetTourByIdRequest
	(*GetTourByIdResponse)(nil), // 3: GetTourByIdResponse
	(*PublishTourRequest)(nil),  // 4: PublishTourRequest
	(*PublishTourResponse)(nil), // 5: PublishTourResponse
}
var file_tour_service_proto_depIdxs = []int32{
	0, // 0: Tour.transportTimes:type_name -> TransportTime
	1, // 1: GetTourByIdResponse.tour:type_name -> Tour
	1, // 2: PublishTourResponse.tour:type_name -> Tour
	2, // 3: TourService.GetTourById:input_type -> GetTourByIdRequest
	4, // 4: TourService.PublishTour:input_type -> PublishTourRequest
	3, // 5: TourService.GetTourById:output_type -> GetTourByIdResponse
	5, // 6: TourService.PublishTour:output_type -> PublishTourResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tour_service_proto_init() }
func file_tour_service_proto_init() {
	if File_tour_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tour_service_proto_rawDesc), len(file_tour_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_service_proto_goTypes,
		DependencyIndexes: file_tour_service_proto_depIdxs,
		MessageInfos:      file_tour_service_proto_msgTypes,
	}.Build()
	File_tour_service_proto = out.File
	file_tour_service_proto_goTypes = nil
	file_tour_service_proto_depIdxs = nil
}
